Refinement
Roksik/floweis pull request #1
Opened 2017-05-30 20:03 UTC by Roksik

2017-05-30 20:12 UTC, ilnario requested changes

2017-05-30 20:12 UTC, ilnario commented on index.html
> +				<div class="condition">*Скидка предоставляется при заказе от 5 штук</div></div>
Лишний закрывающий див

2017-05-30 20:12 UTC, ilnario commented on index.html
> +			<div class="logo"><img class="nanoplast" src="images/logo_nanoplast.png">
И эту картинку тоже нужно унести в цсс

2017-05-30 20:12 UTC, ilnario commented on style.css
> +	margin-left: -50px;
Объеденить с верхним марджином

2017-05-30 20:22 UTC, Roksik commented on index.html
> +				<div class="condition">*Скидка предоставляется при заказе от 5 штук</div></div>
где именно лишний? в 98 строке он от 97ой, объединяет две строки

2017-05-30 20:56 UTC, ilnario commented on index.html
> +				<div class="condition">*Скидка предоставляется при заказе от 5 штук</div></div>
Тогда нужно перенести его на новую строку, а внутренний элемент condition сдвинуть на 1 таб.

2017-06-05 11:23 UTC, Roksik commented on index.html
> +			<div class="logo"><img class="nanoplast" src="images/logo_nanoplast.png">
сделала)

2017-06-05 19:14 UTC, Roksik commented on index.html
> +				<div class="condition">*Скидка предоставляется при заказе от 5 штук</div></div>
done

2017-06-05 19:15 UTC, Roksik commented on style.css
> +	margin-left: -50px;
ерунда получается

2017-06-14 21:26 UTC, ilnario commented on style.css
> +	display: inline-block;
А если там используешь span, то можно обойтись без этого свойства.

2017-06-14 21:26 UTC, ilnario commented on index.html
> +				<div class="phone">+7 (903) <span class="phone_big">902 92 77</span></div>
спустить спан на новую строчку

2017-06-14 21:26 UTC, ilnario commented on index.html
> +				<div class="button"><a href="#">ЗАКАЗАТЬ ЗВОНОК</a></div>
Такую кнопку можно сделать через один тэг.

2017-06-14 21:26 UTC, ilnario commented on index.html
>  				<div class="new_price">936 <span class="new_small">&#8381/шт.</span></div>
Здесь и ниже перенести спан на отдельную строчку.

2017-06-14 21:26 UTC, ilnario commented on index.html
> +				<li>Немецкое качество <div class="flag"><img src="images/flag.png" /></div></li>
Можно сделать флаг через картинку с классов flag

2017-06-14 21:26 UTC, ilnario commented on index.html
> +			</div>
Тут имелось ввиду другое - один тег с двумя классами:
1. slider_button - класс с базовыми стилями
2. slider_button_prev - класс с специфичными стилями для левой кнопки.

2017-06-14 21:26 UTC, ilnario commented on index.html
> +			<div class="doctors_opinion">
Доктора и кнопки переключения не должны быть соседями. У докторов свой родитель - doctros-list

2017-06-14 21:26 UTC, ilnario commented on index.html
> +				<div class="phone">+7 (903) <span class="phone_big">902 92 77</span></div>
перенести спан

2017-06-14 21:31 UTC, ilnario commented on style.css
> +	bottom:0;
Пробел после :

2017-06-14 21:32 UTC, ilnario commented on style.css
> +	font-family: Helvetica_Neue;
Тут и везде необходимо указывать семейство шрифтов

2017-06-14 21:35 UTC, ilnario commented on style.css
> +    font: 16px italic georgia ;
Лишний пробел.

2017-06-14 21:36 UTC, ilnario commented on style.css
>  .second_line_10
Плохая практика формирования класса на основе демо-данных . Скидка может быть и 146%

2017-06-14 21:51 UTC, Roksik commented on index.html
> +				<div class="button"><a href="#">ЗАКАЗАТЬ ЗВОНОК</a></div>
не поняла(

2017-06-14 22:03 UTC, ilnario commented on index.html
> +				<div class="button"><a href="#">ЗАКАЗАТЬ ЗВОНОК</a></div>
Почему бы не объеденить стили селекторов .button a и .button? и убрать тэг див

2017-06-15 18:08 UTC, Roksik commented on index.html
> +			<div class="doctors_opinion">
сделала, кнопки сдвинулись(

2017-06-15 18:09 UTC, Roksik commented on index.html
> +				<li>Немецкое качество <div class="flag"><img src="images/flag.png" /></div></li>
не поняла, добавить флаг через css?

2017-06-15 18:17 UTC, Roksik commented on style.css
> +	font-family: Helvetica_Neue;
т.е. font-family: Helvetica_Neue , sans-serif;   - так?

2017-06-15 18:20 UTC, Roksik commented on index.html
> +			</div>
у меня так и есть кажется

2017-06-15 19:31 UTC, ilnario commented on index.html
> +			</div>
У тебя два тега, а не один.

2017-06-15 19:31 UTC, ilnario commented on index.html
> +			<div class="doctors_opinion">
Значит надо поправить)

2017-06-15 19:32 UTC, ilnario commented on style.css
> +	font-family: Helvetica_Neue;
Ага, правильно.

2017-07-12 19:35 UTC, ilnario commented on index.html
> +				<div class="button"><a href="#">ЗАКАЗАТЬ ЗВОНОК</a></div>
Вот это доделать нужно.

2017-07-12 19:37 UTC, ilnario commented on index.html
> +				<li>Немецкое качество <div class="flag"><img src="images/flag.png" /></div></li>
Ага, сделать через дополнительный класс для ли <li class="draxler">

2017-07-12 19:39 UTC, ilnario commented on style.css
> +	bottom:0;
снова пропал пробел)

2017-07-12 19:40 UTC, ilnario commented on style.css
> +	font-family: Helvetica_Neue;
Тоже нужно доделать.

2017-07-12 19:53 UTC, ilnario commented on style.css
>  {
Удалить неиспользуемые файлы шрифтов и декларации в цсс.

2017-07-12 19:53 UTC, ilnario commented on index.html
> +	<meta charset="utf-8">
Добавить favicon.

2017-07-12 19:53 UTC, ilnario commented on index.html
> +	<title></title>
Определить тайтл.

2017-07-12 19:53 UTC, ilnario commented on index.html
> +			<div class="line"></div>
Стрелку сделать через псевдоэлементы header

2017-07-12 19:53 UTC, ilnario commented on index.html
> +		<div class="dentist"><img src="images/dentist.png" />
перенести img на новую строку

2017-07-12 19:53 UTC, ilnario commented on style.css
> +    background-repeat: no-repeat;
-image и repeat объеденить в одно свойство

2017-07-12 19:53 UTC, ilnario commented on style.css
> +    font-family: Helvetica_Neue_medium sans-serif;
между названиями шрифтов - запятушка)

2017-07-12 19:53 UTC, ilnario commented on style.css
> +    padding: 10x;
выпивала?))

2017-07-12 19:53 UTC, ilnario commented on style.css
> +    background-repeat: no-repeat;
объединить тут и везде

2017-07-12 20:23 UTC, Roksik commented on style.css
> +	bottom:0;
тут всё ок

2017-07-12 20:45 UTC, Roksik commented on style.css
> +    padding: 10x;
в смысле? там ювелирная работа была!!

2017-07-13 16:57 UTC, Roksik commented on style.css
>  {
в css нет лишнего ничего

2017-07-13 17:38 UTC, Roksik commented on index.html
> +	<meta charset="utf-8">
а я умею?)
не вышло...

2017-07-13 17:46 UTC, Roksik commented on index.html
> +			<div class="line"></div>
у меня и так точка у стрелки через псевдоэлемент сделана. line::before. я не могу убрать тег line вообще

2017-07-13 17:53 UTC, ilnario commented on style.css
> +    margin-bottom: 2px;
Объеденить 2 маргина

2017-07-13 17:54 UTC, ilnario commented on style.css
> +	background-repeat: no-repeat;
Объеденить с верхним свойством.

2017-07-13 17:58 UTC, ilnario commented on style.css
>  {
а файлы лишние точно есть

2017-07-13 18:01 UTC, ilnario commented on index.html
> +				<li>Немецкое качество <div class="flag"><img src="images/flag.png" /></div></li>
Пока не исправлено

2017-07-13 18:03 UTC, Roksik commented on style.css
> +	background-repeat: no-repeat;
странно, я то объединила репит и фото фона

2017-07-13 18:03 UTC, Roksik commented on style.css
> +	background-repeat: no-repeat;
еще вчера

2017-07-13 18:03 UTC, ilnario commented on style.css
> +	bottom:0;
как это ок? пробела нет !

2017-07-13 18:07 UTC, ilnario commented on index.html
> +	<meta charset="utf-8">
загугли про favicon, нужно подготовить картинку в фотошопе и корректно вставить

2017-07-13 18:09 UTC, ilnario commented on index.html
> +			<div class="line"></div>
можешь, я в тебя верю) теперь и палочку сделай через афтер

2017-07-13 18:10 UTC, ilnario commented on index.html
> +		<div class="dentist"><img src="images/dentist.png" />
там что-то с отступами у картинки

2017-07-13 18:12 UTC, Roksik commented on index.html
> +			<div class="line"></div>
блин но точка это Line::after  как мне потом прописать точке свойства если line не будет существовать??

2017-07-13 18:12 UTC, ilnario commented on index.html
> +
лишняя пустая строка

2017-07-13 18:14 UTC, ilnario commented on index.html
> +		<div class="info"><a href="#"><img src="images/plane.png" /></a><p>Доставка по всей России<br>любой транспортной компанией:</p></div>
Это мы ещё не обсуждали. Строка не должна быть длинее 120 символов, поэтому, ссылку и параграф переноси на новые строчки.

2017-07-13 19:14 UTC, Roksik commented on index.html
> +				<li>Немецкое качество <div class="flag"><img src="images/flag.png" /></div></li>
исправлено

2017-07-14 14:55 UTC, merged